service: alameda-cee-api-demo

volumes:
  - /var/lib/alameda-cee/demo-data:/data

registry:
  server: ghcr.io
  username: focus-digital
  password:
    - REGISTRY_PASSWORD

env:
  clear:
    TENANT_ID: demo
    ALLOWED_ORIGIN: "https://alameda-cee-demo.focus-labs.io"
    DEMO_MODE: true
  secret:
    - ANTHROPIC_API_KEY
    - EMAIL_SERVICE_API_TOKEN

proxy:
  host: alameda-cee-demo-api.focus-labs.io
