import type { PrismaClient } from '@prisma/client';

import {
  UserRole,
  ProviderType,
  CareType,
  AgeRange,
} from '@/domain/enums.js';
import { AuthService } from '@/service/authService.js';
import { UserService } from '@/service/userService.js';
import { ProviderService } from '@/service/providerService.js';

const DEFAULT_PASSWORD = await AuthService.hashPassword('secret123');

export async function resetDatabase(prisma: PrismaClient): Promise<void> {
  await prisma.$transaction([
    prisma.interestNote.deleteMany(),
    prisma.interest.deleteMany(),
    prisma.provider.deleteMany(),
    prisma.application.deleteMany(),
    prisma.user.deleteMany(),
  ]);
}

export async function runDemoSeed(prisma: PrismaClient): Promise<void> {
  console.log('Running demo seed');

  const userService = new UserService(prisma);
  const providerService = new ProviderService(prisma);

  await createUsers(userService);
  await createProviders(providerService);

  console.log('Done with demo seed');
}

async function createUsers(userService: UserService) {
  console.log('Creating users');
  await userService.ensureUser({
    email: 'jdoe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    role: UserRole.USER,
    passwordHash: DEFAULT_PASSWORD,
  });

  await userService.ensureUser({
    email: 'admin@example.com',
    firstName: 'Admin',
    lastName: 'User',
    role: UserRole.ADMIN,
    passwordHash: DEFAULT_PASSWORD,
  });

  console.log('Done creating users');
}

async function createProviders(providerService: ProviderService) {
  console.log('Creating providers');

  const providers = [
    // === ALAMEDA (94501, 94502) ===
    {
      name: 'Bright Horizons Child Development',
      type: ProviderType.CENTER_BASED,
      address: '900 Webster Street',
      city: 'Alameda',
      zipCode: '94501',
      latitude: 37.7652,
      longitude: -122.2416,
      phone: '(510) 555-0101',
      email: 'alameda@brighthorizons.example.com',
      descriptionEn: 'Full-service child care center serving infants through school-age children. Before and after school programs available with transportation from local schools.',
      descriptionEs: 'Centro de cuidado infantil de servicio completo que atiende desde bebés hasta niños en edad escolar. Programas antes y después de la escuela disponibles con transporte desde escuelas locales.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL, AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.FULL_DAY, CareType.BEFORE_AFTER_SCHOOL],
      isActive: true,
    },
    {
      name: 'Alameda Island Kids',
      type: ProviderType.CENTER_BASED,
      address: '2100 Central Avenue',
      city: 'Alameda',
      zipCode: '94501',
      latitude: 37.7701,
      longitude: -122.2677,
      phone: '(510) 555-0102',
      email: 'hello@alamedaislandkids.example.com',
      descriptionEn: 'Beach-inspired early childhood center with outdoor nature curriculum. Daily outdoor exploration and age-appropriate beach trips during summer months.',
      descriptionEs: 'Centro de primera infancia inspirado en la playa con currículo de naturaleza al aire libre. Exploración diaria al aire libre y excursiones a la playa apropiadas para cada edad durante los meses de verano.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.PRESCHOOL, AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.FULL_DAY, CareType.BEFORE_AFTER_SCHOOL],
      isActive: true,
    },
    {
      name: 'Mama Chen Family Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '1456 Park Street',
      city: 'Alameda',
      zipCode: '94501',
      latitude: 37.7634,
      longitude: -122.2439,
      phone: '(510) 555-0103',
      descriptionEn: 'Bilingual Cantonese/English family child care. Healthy Asian-inspired meals, quiet nap environment, and focus on early literacy.',
      descriptionEs: 'Cuidado infantil familiar bilingüe cantonés/inglés. Comidas saludables de inspiración asiática, ambiente tranquilo para la siesta y enfoque en alfabetización temprana.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },
    {
      name: 'Bay Farm Preschool',
      type: ProviderType.CENTER_BASED,
      address: '3000 Island Drive',
      city: 'Alameda',
      zipCode: '94502',
      latitude: 37.7375,
      longitude: -122.2400,
      phone: '(510) 555-0104',
      email: 'info@bayfarmpreschool.example.com',
      descriptionEn: 'Nature-based preschool program on Bay Farm Island. Large outdoor spaces, gardening program, and STEM exploration.',
      descriptionEs: 'Programa preescolar basado en la naturaleza en Bay Farm Island. Amplios espacios al aire libre, programa de jardinería y exploración STEM.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },
    {
      name: 'Harbor Bay Kids Club',
      type: ProviderType.CENTER_BASED,
      address: '1245 Harbor Bay Parkway',
      city: 'Alameda',
      zipCode: '94502',
      latitude: 37.7312,
      longitude: -122.2345,
      phone: '(510) 555-0105',
      email: 'harborbay@kidsclub.example.com',
      descriptionEn: 'School-age focused program with homework help, enrichment activities, and summer camps. Transportation from local elementary schools.',
      descriptionEs: 'Programa enfocado en edad escolar con ayuda con tareas, actividades de enriquecimiento y campamentos de verano. Transporte desde escuelas primarias locales.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.BEFORE_AFTER_SCHOOL],
      isActive: true,
    },

    // === OAKLAND - FRUITVALE/SAN ANTONIO (94601) ===
    {
      name: 'Sunshine Family Child Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '1234 Oak Street',
      city: 'Oakland',
      zipCode: '94601',
      latitude: 37.7751,
      longitude: -122.2246,
      phone: '(510) 555-0201',
      email: 'sunshine@example.com',
      descriptionEn: 'Nurturing home-based care for infants and toddlers in a warm, family environment. Bilingual Spanish/English program with nutritious homemade meals.',
      descriptionEs: 'Cuidado hogareño y cariñoso para bebés y niños pequeños en un ambiente familiar cálido. Programa bilingüe español/inglés con comidas caseras nutritivas.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },
    {
      name: 'Abuela Rosa Family Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '2345 Fruitvale Avenue',
      city: 'Oakland',
      zipCode: '94601',
      latitude: 37.7749,
      longitude: -122.2194,
      phone: '(510) 555-0202',
      descriptionEn: 'Spanish-immersion family child care with 20+ years of experience. Homemade Latin American cuisine and cultural activities. Small group sizes for personalized attention.',
      descriptionEs: 'Cuidado infantil familiar de inmersión en español con más de 20 años de experiencia. Cocina latinoamericana casera y actividades culturales. Grupos pequeños para atención personalizada.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },
    {
      name: 'Fruitvale Early Learning Center',
      type: ProviderType.CENTER_BASED,
      address: '3401 International Boulevard',
      city: 'Oakland',
      zipCode: '94601',
      latitude: 37.7756,
      longitude: -122.2147,
      phone: '(510) 555-0203',
      email: 'fruitvale@earlylearning.example.com',
      descriptionEn: 'Community-based center serving diverse families. Dual-language Spanish/English curriculum, parent engagement programs, and family support services.',
      descriptionEs: 'Centro comunitario que sirve a familias diversas. Currículo bilingüe español/inglés, programas de participación de padres y servicios de apoyo familiar.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },

    // === OAKLAND - DIMOND/GLENVIEW (94602) ===
    {
      name: 'Dimond Discovery Preschool',
      type: ProviderType.CENTER_BASED,
      address: '3890 MacArthur Boulevard',
      city: 'Oakland',
      zipCode: '94602',
      latitude: 37.8028,
      longitude: -122.2088,
      phone: '(510) 555-0301',
      email: 'info@dimonddiscovery.example.com',
      descriptionEn: 'Play-based preschool in the heart of the Dimond District. Focus on creative arts, outdoor exploration, and social-emotional development.',
      descriptionEs: 'Preescolar basado en el juego en el corazón del Distrito Dimond. Enfoque en artes creativas, exploración al aire libre y desarrollo socioemocional.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },
    {
      name: 'Glenview Family Child Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '4521 Park Boulevard',
      city: 'Oakland',
      zipCode: '94602',
      latitude: 37.8045,
      longitude: -122.2134,
      phone: '(510) 555-0302',
      descriptionEn: 'Cozy home-based care in quiet Glenview neighborhood. Large backyard play area, organic meals, and focus on early literacy.',
      descriptionEs: 'Cuidado hogareño acogedor en el tranquilo vecindario de Glenview. Amplia área de juego en el patio, comidas orgánicas y enfoque en alfabetización temprana.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },

    // === OAKLAND - EAST OAKLAND (94603) ===
    {
      name: 'Sobrante Park Learning Center',
      type: ProviderType.CENTER_BASED,
      address: '7800 Lockwood Street',
      city: 'Oakland',
      zipCode: '94603',
      latitude: 37.7512,
      longitude: -122.1823,
      phone: '(510) 555-0401',
      email: 'sobrantepark@learning.example.com',
      descriptionEn: 'Community learning center offering free and low-cost childcare. Head Start partner with comprehensive family services.',
      descriptionEs: 'Centro de aprendizaje comunitario que ofrece cuidado infantil gratuito y de bajo costo. Socio de Head Start con servicios integrales para familias.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },
    {
      name: 'Tia Maria Family Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '8234 Holly Street',
      city: 'Oakland',
      zipCode: '94603',
      latitude: 37.7489,
      longitude: -122.1756,
      phone: '(510) 555-0402',
      descriptionEn: 'Bilingual Spanish/English family care with warm, loving environment. Focus on kindergarten readiness and cultural pride.',
      descriptionEs: 'Cuidado familiar bilingüe español/inglés con ambiente cálido y amoroso. Enfoque en preparación para kindergarten y orgullo cultural.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },

    // === OAKLAND - MAXWELL PARK/SEMINARY (94605) ===
    {
      name: 'Maxwell Park Children Center',
      type: ProviderType.CENTER_BASED,
      address: '5714 Foothill Boulevard',
      city: 'Oakland',
      zipCode: '94605',
      latitude: 37.7798,
      longitude: -122.1912,
      phone: '(510) 555-0501',
      email: 'maxwellpark@children.example.com',
      descriptionEn: 'Neighborhood center with strong community ties. Art-focused curriculum with visiting artists and gallery exhibitions of children work.',
      descriptionEs: 'Centro de vecindario con fuertes lazos comunitarios. Currículo enfocado en el arte con artistas visitantes y exhibiciones de galería del trabajo de los niños.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.PRESCHOOL, AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.FULL_DAY, CareType.BEFORE_AFTER_SCHOOL],
      isActive: true,
    },
    {
      name: 'Seminary Stars Family Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '6100 Seminary Avenue',
      city: 'Oakland',
      zipCode: '94605',
      latitude: 37.7823,
      longitude: -122.1845,
      phone: '(510) 555-0502',
      descriptionEn: 'Licensed family child care with flexible hours for working families. Evening care available until 7pm.',
      descriptionEs: 'Cuidado infantil familiar licenciado con horarios flexibles para familias trabajadoras. Cuidado nocturno disponible hasta las 7pm.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },

    // === OAKLAND - LAKE MERRITT/EASTLAKE (94606) ===
    {
      name: 'Happy Hearts Family Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '789 Park Boulevard',
      city: 'Oakland',
      zipCode: '94606',
      latitude: 37.7925,
      longitude: -122.2512,
      phone: '(510) 555-0601',
      descriptionEn: 'Licensed family child care providing loving care in a home environment. Flexible scheduling available including drop-in care when space permits.',
      descriptionEs: 'Cuidado infantil familiar licenciado que brinda atención amorosa en un ambiente hogareño. Horarios flexibles disponibles incluyendo cuidado ocasional cuando hay espacio.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.DROP_IN],
      isActive: true,
    },
    {
      name: 'Lake Merritt Early Academy',
      type: ProviderType.CENTER_BASED,
      address: '1800 Lakeshore Avenue',
      city: 'Oakland',
      zipCode: '94606',
      latitude: 37.7987,
      longitude: -122.2456,
      phone: '(510) 555-0602',
      email: 'lakemerritt@earlyacademy.example.com',
      descriptionEn: 'Urban preschool with daily walks around Lake Merritt. Focus on nature education, physical activity, and community engagement.',
      descriptionEs: 'Preescolar urbano con caminatas diarias alrededor del Lago Merritt. Enfoque en educación sobre la naturaleza, actividad física y participación comunitaria.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },

    // === OAKLAND - WEST OAKLAND (94607) ===
    {
      name: 'Oakland Community Preschool',
      type: ProviderType.CENTER_BASED,
      address: '1500 14th Street',
      city: 'Oakland',
      zipCode: '94607',
      latitude: 37.8071,
      longitude: -122.2887,
      phone: '(510) 555-0701',
      email: 'enroll@oaklandpreschool.example.com',
      descriptionEn: 'Non-profit community preschool with sliding scale fees. Play-based curriculum emphasizing social-emotional development and creative expression.',
      descriptionEs: 'Preescolar comunitario sin fines de lucro con tarifas escalonadas. Currículo basado en el juego que enfatiza el desarrollo socioemocional y la expresión creativa.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },
    {
      name: 'West Oakland Head Start',
      type: ProviderType.CENTER_BASED,
      address: '1025 Center Street',
      city: 'Oakland',
      zipCode: '94607',
      latitude: 37.8089,
      longitude: -122.2934,
      phone: '(510) 555-0702',
      email: 'westoakland@headstart.example.com',
      descriptionEn: 'Federal Head Start program serving low-income families. Comprehensive services including health screenings, nutrition, and parent education.',
      descriptionEs: 'Programa federal Head Start que sirve a familias de bajos ingresos. Servicios integrales incluyendo exámenes de salud, nutrición y educación para padres.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },

    // === OAKLAND - EMERYVILLE BORDER (94608) ===
    {
      name: 'MacArthur BART Kids',
      type: ProviderType.CENTER_BASED,
      address: '401 40th Street',
      city: 'Oakland',
      zipCode: '94608',
      latitude: 37.8289,
      longitude: -122.2671,
      phone: '(510) 555-0801',
      email: 'macarthur@bartkids.example.com',
      descriptionEn: 'Convenient childcare near MacArthur BART. Extended hours for commuting parents. Drop-off as early as 6:30am.',
      descriptionEs: 'Cuidado infantil conveniente cerca del BART MacArthur. Horario extendido para padres que viajan al trabajo. Llegada desde las 6:30am.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL, AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.FULL_DAY, CareType.BEFORE_AFTER_SCHOOL],
      isActive: true,
    },
    {
      name: 'Longfellow Family Child Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '5123 Adeline Street',
      city: 'Oakland',
      zipCode: '94608',
      latitude: 37.8312,
      longitude: -122.2756,
      phone: '(510) 555-0802',
      descriptionEn: 'Diverse, inclusive family child care celebrating all cultures. Multicultural curriculum with music and dance from around the world.',
      descriptionEs: 'Cuidado infantil familiar diverso e inclusivo que celebra todas las culturas. Currículo multicultural con música y danza de todo el mundo.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },

    // === OAKLAND - TEMESCAL/ROCKRIDGE (94609) ===
    {
      name: 'East Bay Learning Center',
      type: ProviderType.CENTER_BASED,
      address: '4500 Telegraph Avenue',
      city: 'Oakland',
      zipCode: '94609',
      latitude: 37.8349,
      longitude: -122.2625,
      phone: '(510) 555-0901',
      email: 'info@eastbaylearning.example.com',
      descriptionEn: 'Montessori-inspired early learning center with mixed-age classrooms. Focus on independence, hands-on learning, and respect for each child unique development.',
      descriptionEs: 'Centro de aprendizaje temprano inspirado en Montessori con aulas de edades mixtas. Enfoque en independencia, aprendizaje práctico y respeto por el desarrollo único de cada niño.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL, AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.FULL_DAY, CareType.BEFORE_AFTER_SCHOOL],
      isActive: true,
    },
    {
      name: 'Temescal Tot Spot',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '4623 Clarke Street',
      city: 'Oakland',
      zipCode: '94609',
      latitude: 37.8367,
      longitude: -122.2589,
      phone: '(510) 555-0902',
      descriptionEn: 'Reggio Emilia inspired family child care. Project-based learning, natural materials, and documentation of children learning journey.',
      descriptionEs: 'Cuidado infantil familiar inspirado en Reggio Emilia. Aprendizaje basado en proyectos, materiales naturales y documentación del viaje de aprendizaje de los niños.',
      acceptsSubsidy: false,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },

    // === OAKLAND - PIEDMONT AVE/MONTCLAIR (94610, 94611) ===
    {
      name: 'Piedmont Avenue Preschool',
      type: ProviderType.CENTER_BASED,
      address: '4100 Piedmont Avenue',
      city: 'Oakland',
      zipCode: '94611',
      latitude: 37.8278,
      longitude: -122.2512,
      phone: '(510) 555-1001',
      email: 'piedmont@preschool.example.com',
      descriptionEn: 'Cooperative preschool with strong parent involvement. Play-based curriculum in historic building with beautiful garden.',
      descriptionEs: 'Preescolar cooperativo con fuerte participación de los padres. Currículo basado en el juego en edificio histórico con hermoso jardín.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.PART_DAY],
      isActive: true,
    },
    {
      name: 'Montclair Kids Academy',
      type: ProviderType.CENTER_BASED,
      address: '6200 Moraga Avenue',
      city: 'Oakland',
      zipCode: '94611',
      latitude: 37.8356,
      longitude: -122.2134,
      phone: '(510) 555-1002',
      email: 'montclair@kidsacademy.example.com',
      descriptionEn: 'Premium early learning in Oakland hills. Small class sizes, enrichment programs, and summer camp options.',
      descriptionEs: 'Aprendizaje temprano premium en las colinas de Oakland. Clases pequeñas, programas de enriquecimiento y opciones de campamento de verano.',
      acceptsSubsidy: false,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL, AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.FULL_DAY, CareType.BEFORE_AFTER_SCHOOL],
      isActive: true,
    },
    {
      name: 'Lakeshore Family Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '3456 Lakeshore Avenue',
      city: 'Oakland',
      zipCode: '94610',
      latitude: 37.8112,
      longitude: -122.2389,
      phone: '(510) 555-1003',
      descriptionEn: 'Experienced provider near Lakeshore shops. Daily walks to Grand Lake, focus on early math and literacy skills.',
      descriptionEs: 'Proveedora experimentada cerca de las tiendas de Lakeshore. Caminatas diarias al Grand Lake, enfoque en matemáticas tempranas y habilidades de alfabetización.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },

    // === OAKLAND - DOWNTOWN (94612) ===
    {
      name: 'Little Learners Academy',
      type: ProviderType.CENTER_BASED,
      address: '5678 Broadway',
      city: 'Oakland',
      zipCode: '94612',
      latitude: 37.8044,
      longitude: -122.2712,
      phone: '(510) 555-1101',
      email: 'info@littlelearners.example.com',
      descriptionEn: 'State-licensed center offering comprehensive early childhood education with a focus on kindergarten readiness. STEM curriculum and outdoor play areas.',
      descriptionEs: 'Centro licenciado por el estado que ofrece educación infantil integral con enfoque en preparación para kindergarten. Currículo STEM y áreas de juego al aire libre.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },
    {
      name: 'Downtown Oakland Child Care',
      type: ProviderType.CENTER_BASED,
      address: '1901 Franklin Street',
      city: 'Oakland',
      zipCode: '94612',
      latitude: 37.8067,
      longitude: -122.2689,
      phone: '(510) 555-1102',
      email: 'downtown@childcare.example.com',
      descriptionEn: 'Convenient downtown location for working parents. Near 19th Street BART with extended hours until 6:30pm.',
      descriptionEs: 'Ubicación céntrica conveniente para padres trabajadores. Cerca del BART de la calle 19 con horario extendido hasta las 6:30pm.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },

    // === OAKLAND - UPPER ROCKRIDGE (94618) ===
    {
      name: 'Rockridge Little School',
      type: ProviderType.CENTER_BASED,
      address: '5435 College Avenue',
      city: 'Oakland',
      zipCode: '94618',
      latitude: 37.8412,
      longitude: -122.2523,
      phone: '(510) 555-1201',
      email: 'info@rockridgelittle.example.com',
      descriptionEn: 'Boutique preschool in the heart of Rockridge. Waldorf-inspired curriculum with emphasis on imaginative play and natural materials.',
      descriptionEs: 'Preescolar boutique en el corazón de Rockridge. Currículo inspirado en Waldorf con énfasis en juego imaginativo y materiales naturales.',
      acceptsSubsidy: false,
      ageRangesServed: [AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },

    // === OAKLAND - LAUREL/REDWOOD HEIGHTS (94619) ===
    {
      name: 'Laurel Village Preschool',
      type: ProviderType.CENTER_BASED,
      address: '3825 MacArthur Boulevard',
      city: 'Oakland',
      zipCode: '94619',
      latitude: 37.7934,
      longitude: -122.1978,
      phone: '(510) 555-1301',
      email: 'laurel@preschool.example.com',
      descriptionEn: 'Community preschool in the Laurel District. Strong emphasis on outdoor play, gardening, and environmental education.',
      descriptionEs: 'Preescolar comunitario en el Distrito Laurel. Fuerte énfasis en juego al aire libre, jardinería y educación ambiental.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },
    {
      name: 'Redwood Heights Family Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '4012 39th Avenue',
      city: 'Oakland',
      zipCode: '94619',
      latitude: 37.7978,
      longitude: -122.2034,
      phone: '(510) 555-1302',
      descriptionEn: 'Quiet hillside family child care with spacious backyard. Focus on sensory play and early science exploration.',
      descriptionEs: 'Cuidado infantil familiar tranquilo en la ladera con amplio patio trasero. Enfoque en juego sensorial y exploración científica temprana.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },

    // === OAKLAND - COLISEUM/ELMHURST (94621) ===
    {
      name: 'Elmhurst Early Learning',
      type: ProviderType.CENTER_BASED,
      address: '1450 92nd Avenue',
      city: 'Oakland',
      zipCode: '94621',
      latitude: 37.7456,
      longitude: -122.1834,
      phone: '(510) 555-1401',
      email: 'elmhurst@earlylearning.example.com',
      descriptionEn: 'Head Start program serving Elmhurst community. Bilingual staff, family support services, and free meals for qualifying families.',
      descriptionEs: 'Programa Head Start que sirve a la comunidad de Elmhurst. Personal bilingüe, servicios de apoyo familiar y comidas gratis para familias que califican.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },
    {
      name: 'Coliseum Kids Family Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '8901 International Boulevard',
      city: 'Oakland',
      zipCode: '94621',
      latitude: 37.7489,
      longitude: -122.1712,
      phone: '(510) 555-1402',
      descriptionEn: 'Affordable family child care with flexible schedules. Accepts night and weekend hours for shift workers.',
      descriptionEs: 'Cuidado infantil familiar asequible con horarios flexibles. Acepta horarios nocturnos y de fin de semana para trabajadores por turnos.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.DROP_IN],
      isActive: true,
    },

    // === BERKELEY (94702, 94703, 94704, 94705, 94707, 94708, 94709, 94710) ===
    {
      name: 'Berkeley Montessori School',
      type: ProviderType.CENTER_BASED,
      address: '2020 Virginia Street',
      city: 'Berkeley',
      zipCode: '94709',
      latitude: 37.8756,
      longitude: -122.2689,
      phone: '(510) 555-1501',
      email: 'info@berkeleymontessori.example.com',
      descriptionEn: 'Authentic Montessori education with AMI-trained teachers. Mixed-age classrooms promoting independence and self-directed learning.',
      descriptionEs: 'Educación Montessori auténtica con maestros capacitados por AMI. Aulas de edades mixtas que promueven la independencia y el aprendizaje autodirigido.',
      acceptsSubsidy: false,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },
    {
      name: 'South Berkeley Family Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '2912 Adeline Street',
      city: 'Berkeley',
      zipCode: '94703',
      latitude: 37.8534,
      longitude: -122.2756,
      phone: '(510) 555-1502',
      descriptionEn: 'Warm family environment in South Berkeley. Diverse community, vegetarian meals, and daily outdoor time at local parks.',
      descriptionEs: 'Ambiente familiar cálido en el sur de Berkeley. Comunidad diversa, comidas vegetarianas y tiempo diario al aire libre en parques locales.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },
    {
      name: 'Downtown Berkeley Child Development',
      type: ProviderType.CENTER_BASED,
      address: '2121 Shattuck Avenue',
      city: 'Berkeley',
      zipCode: '94704',
      latitude: 37.8712,
      longitude: -122.2678,
      phone: '(510) 555-1503',
      email: 'downtown@berkeleychilddev.example.com',
      descriptionEn: 'Near UC Berkeley campus. Popular with graduate student families. Sliding scale fees and research-based curriculum.',
      descriptionEs: 'Cerca del campus de UC Berkeley. Popular entre familias de estudiantes de posgrado. Tarifas escalonadas y currículo basado en investigación.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },
    {
      name: 'West Berkeley Preschool',
      type: ProviderType.CENTER_BASED,
      address: '1200 5th Street',
      city: 'Berkeley',
      zipCode: '94710',
      latitude: 37.8823,
      longitude: -122.2923,
      phone: '(510) 555-1504',
      email: 'westberkeley@preschool.example.com',
      descriptionEn: 'Arts-focused preschool in converted warehouse space. Large indoor play area, visiting artists, and emphasis on creative expression.',
      descriptionEs: 'Preescolar enfocado en las artes en un almacén convertido. Amplia área de juego interior, artistas visitantes y énfasis en la expresión creativa.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },
    {
      name: 'North Berkeley Family Child Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '1567 Hopkins Street',
      city: 'Berkeley',
      zipCode: '94707',
      latitude: 37.8889,
      longitude: -122.2734,
      phone: '(510) 555-1505',
      descriptionEn: 'Experienced provider in quiet North Berkeley neighborhood. Garden-based curriculum with composting and cooking activities.',
      descriptionEs: 'Proveedora experimentada en el tranquilo vecindario del norte de Berkeley. Currículo basado en el jardín con actividades de compostaje y cocina.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },
    {
      name: 'Claremont Kids Center',
      type: ProviderType.CENTER_BASED,
      address: '2900 Claremont Avenue',
      city: 'Berkeley',
      zipCode: '94705',
      latitude: 37.8567,
      longitude: -122.2456,
      phone: '(510) 555-1506',
      email: 'claremont@kidscenter.example.com',
      descriptionEn: 'Nature-based program near Claremont Canyon. Daily hikes, forest school philosophy, and strong focus on environmental stewardship.',
      descriptionEs: 'Programa basado en la naturaleza cerca del Cañón Claremont. Caminatas diarias, filosofía de escuela forestal y fuerte enfoque en la administración ambiental.',
      acceptsSubsidy: false,
      ageRangesServed: [AgeRange.PRESCHOOL, AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.FULL_DAY, CareType.BEFORE_AFTER_SCHOOL],
      isActive: true,
    },

    // === FREMONT (94536, 94538, 94539, 94555) ===
    {
      name: 'Fremont Family Learning Center',
      type: ProviderType.CENTER_BASED,
      address: '37500 Fremont Boulevard',
      city: 'Fremont',
      zipCode: '94536',
      latitude: 37.5485,
      longitude: -121.9886,
      phone: '(510) 555-1601',
      email: 'info@fremontfamily.example.com',
      descriptionEn: 'Large center serving diverse Fremont community. Multilingual staff (English, Spanish, Hindi, Mandarin) and inclusive programming.',
      descriptionEs: 'Centro grande que sirve a la diversa comunidad de Fremont. Personal multilingüe (inglés, español, hindi, mandarín) y programación inclusiva.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL, AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.FULL_DAY, CareType.BEFORE_AFTER_SCHOOL],
      isActive: true,
    },
    {
      name: 'Centerville Family Child Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '4123 Peralta Boulevard',
      city: 'Fremont',
      zipCode: '94536',
      latitude: 37.5512,
      longitude: -121.9823,
      phone: '(510) 555-1602',
      descriptionEn: 'Loving family care in historic Centerville. Focus on early literacy, music, and movement.',
      descriptionEs: 'Cuidado familiar amoroso en el histórico Centerville. Enfoque en alfabetización temprana, música y movimiento.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },
    {
      name: 'Irvington Preschool Academy',
      type: ProviderType.CENTER_BASED,
      address: '41100 Fremont Boulevard',
      city: 'Fremont',
      zipCode: '94538',
      latitude: 37.5234,
      longitude: -121.9612,
      phone: '(510) 555-1603',
      email: 'irvington@preschool.example.com',
      descriptionEn: 'Academic-focused preschool with structured learning environment. Strong kindergarten prep and early reading program.',
      descriptionEs: 'Preescolar con enfoque académico y ambiente de aprendizaje estructurado. Fuerte preparación para kindergarten y programa de lectura temprana.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },
    {
      name: 'Warm Springs Family Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '47200 Warm Springs Boulevard',
      city: 'Fremont',
      zipCode: '94539',
      latitude: 37.4923,
      longitude: -121.9234,
      phone: '(510) 555-1604',
      descriptionEn: 'Near Warm Springs BART. Convenient for commuters with extended hours. Bilingual Mandarin/English program.',
      descriptionEs: 'Cerca del BART Warm Springs. Conveniente para viajeros con horario extendido. Programa bilingüe mandarín/inglés.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },
    {
      name: 'Newark-Fremont Kids Club',
      type: ProviderType.CENTER_BASED,
      address: '39675 Cedar Boulevard',
      city: 'Fremont',
      zipCode: '94538',
      latitude: 37.5356,
      longitude: -121.9567,
      phone: '(510) 555-1605',
      email: 'newarkfremont@kidsclub.example.com',
      descriptionEn: 'School-age focus with homework help, STEM activities, and sports programs. Summer camp and vacation care available.',
      descriptionEs: 'Enfoque en edad escolar con ayuda con tareas, actividades STEM y programas deportivos. Campamento de verano y cuidado vacacional disponibles.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.BEFORE_AFTER_SCHOOL, CareType.DROP_IN],
      isActive: true,
    },
    {
      name: 'Ardenwood Family Child Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '34500 Ardenwood Boulevard',
      city: 'Fremont',
      zipCode: '94555',
      latitude: 37.5589,
      longitude: -122.0234,
      phone: '(510) 555-1606',
      descriptionEn: 'Near Ardenwood Historic Farm with regular field trips. Focus on nature education and farm-to-table cooking.',
      descriptionEs: 'Cerca de la Granja Histórica Ardenwood con excursiones regulares. Enfoque en educación sobre la naturaleza y cocina de la granja a la mesa.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },

    // === HAYWARD (94541, 94544, 94545) ===
    {
      name: 'Hayward Child Development Center',
      type: ProviderType.CENTER_BASED,
      address: '22300 Foothill Boulevard',
      city: 'Hayward',
      zipCode: '94541',
      latitude: 37.6689,
      longitude: -122.0867,
      phone: '(510) 555-1701',
      email: 'hayward@childdev.example.com',
      descriptionEn: 'Large center affiliated with Cal State East Bay. Student teacher training site with research-based practices.',
      descriptionEs: 'Centro grande afiliado a Cal State East Bay. Sitio de capacitación para maestros estudiantes con prácticas basadas en investigación.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },
    {
      name: 'Downtown Hayward Family Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '945 B Street',
      city: 'Hayward',
      zipCode: '94541',
      latitude: 37.6712,
      longitude: -122.0823,
      phone: '(510) 555-1702',
      descriptionEn: 'Walking distance to Hayward BART. Bilingual Spanish/English care with cultural celebrations and homemade meals.',
      descriptionEs: 'A poca distancia a pie del BART de Hayward. Cuidado bilingüe español/inglés con celebraciones culturales y comidas caseras.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },
    {
      name: 'South Hayward Early Learning',
      type: ProviderType.CENTER_BASED,
      address: '28200 Hesperian Boulevard',
      city: 'Hayward',
      zipCode: '94545',
      latitude: 37.6345,
      longitude: -122.0512,
      phone: '(510) 555-1703',
      email: 'southhayward@earlylearning.example.com',
      descriptionEn: 'Head Start and Early Head Start programs. Comprehensive family services including health, nutrition, and parent education.',
      descriptionEs: 'Programas Head Start y Early Head Start. Servicios integrales para familias incluyendo salud, nutrición y educación para padres.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },
    {
      name: 'Jackson Triangle Kids',
      type: ProviderType.CENTER_BASED,
      address: '24500 Amador Street',
      city: 'Hayward',
      zipCode: '94544',
      latitude: 37.6523,
      longitude: -122.0734,
      phone: '(510) 555-1704',
      email: 'jackson@trianglekids.example.com',
      descriptionEn: 'Neighborhood center with strong community ties. After-school programs partnering with local elementary schools.',
      descriptionEs: 'Centro de vecindario con fuertes lazos comunitarios. Programas después de la escuela en asociación con escuelas primarias locales.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.PRESCHOOL, AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.FULL_DAY, CareType.BEFORE_AFTER_SCHOOL],
      isActive: true,
    },
    {
      name: 'Tennyson Family Child Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '25678 Tennyson Road',
      city: 'Hayward',
      zipCode: '94544',
      latitude: 37.6489,
      longitude: -122.0623,
      phone: '(510) 555-1705',
      descriptionEn: 'Experienced provider with 15+ years serving Hayward families. Structured daily routine with focus on school readiness.',
      descriptionEs: 'Proveedora experimentada con más de 15 años sirviendo a familias de Hayward. Rutina diaria estructurada con enfoque en preparación escolar.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },

    // === SAN LEANDRO (94577, 94578, 94579) ===
    {
      name: 'San Leandro Early Learning Center',
      type: ProviderType.CENTER_BASED,
      address: '13855 East 14th Street',
      city: 'San Leandro',
      zipCode: '94578',
      latitude: 37.7089,
      longitude: -122.1545,
      phone: '(510) 555-1801',
      email: 'info@sanleandrolearning.example.com',
      descriptionEn: 'Established center serving San Leandro for over 30 years. Strong parent involvement and community partnerships.',
      descriptionEs: 'Centro establecido que sirve a San Leandro por más de 30 años. Fuerte participación de los padres y asociaciones comunitarias.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },
    {
      name: 'Marina Family Child Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '14500 Doolittle Drive',
      city: 'San Leandro',
      zipCode: '94577',
      latitude: 37.7234,
      longitude: -122.1923,
      phone: '(510) 555-1802',
      descriptionEn: 'Near San Leandro Marina with daily outdoor activities. Focus on physical development and nature appreciation.',
      descriptionEs: 'Cerca de la Marina de San Leandro con actividades diarias al aire libre. Enfoque en desarrollo físico y apreciación de la naturaleza.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },
    {
      name: 'Bayfair Kids Academy',
      type: ProviderType.CENTER_BASED,
      address: '15200 Hesperian Boulevard',
      city: 'San Leandro',
      zipCode: '94578',
      latitude: 37.6956,
      longitude: -122.1289,
      phone: '(510) 555-1803',
      email: 'bayfair@kidsacademy.example.com',
      descriptionEn: 'Convenient location near Bayfair BART. Structured academic program with emphasis on kindergarten readiness.',
      descriptionEs: 'Ubicación conveniente cerca del BART Bayfair. Programa académico estructurado con énfasis en preparación para kindergarten.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.PRESCHOOL, AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.FULL_DAY, CareType.BEFORE_AFTER_SCHOOL],
      isActive: true,
    },
    {
      name: 'Washington Manor Family Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '14789 Manor Boulevard',
      city: 'San Leandro',
      zipCode: '94579',
      latitude: 37.6878,
      longitude: -122.1434,
      phone: '(510) 555-1804',
      descriptionEn: 'Cozy family care in Washington Manor neighborhood. Flexible hours for working families, healthy homemade meals.',
      descriptionEs: 'Cuidado familiar acogedor en el vecindario Washington Manor. Horarios flexibles para familias trabajadoras, comidas caseras saludables.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.DROP_IN],
      isActive: true,
    },

    // === UNION CITY (94587) ===
    {
      name: 'Union City Children Center',
      type: ProviderType.CENTER_BASED,
      address: '33000 Alvarado-Niles Road',
      city: 'Union City',
      zipCode: '94587',
      latitude: 37.5934,
      longitude: -122.0189,
      phone: '(510) 555-1901',
      email: 'unioncity@children.example.com',
      descriptionEn: 'Large center near Union City BART. Diverse community with multilingual staff and cultural celebration programs.',
      descriptionEs: 'Centro grande cerca del BART de Union City. Comunidad diversa con personal multilingüe y programas de celebración cultural.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL, AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.FULL_DAY, CareType.BEFORE_AFTER_SCHOOL],
      isActive: true,
    },
    {
      name: 'Decoto Family Child Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '34500 7th Street',
      city: 'Union City',
      zipCode: '94587',
      latitude: 37.5867,
      longitude: -122.0234,
      phone: '(510) 555-1902',
      descriptionEn: 'Family child care in historic Decoto neighborhood. Spanish/English bilingual with focus on cultural heritage.',
      descriptionEs: 'Cuidado infantil familiar en el histórico vecindario Decoto. Bilingüe español/inglés con enfoque en herencia cultural.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },

    // === CASTRO VALLEY (94546) ===
    {
      name: 'Castro Valley Kids Center',
      type: ProviderType.CENTER_BASED,
      address: '3446 Village Drive',
      city: 'Castro Valley',
      zipCode: '94546',
      latitude: 37.6934,
      longitude: -122.0756,
      phone: '(510) 555-2001',
      email: 'castrovally@kidscenter.example.com',
      descriptionEn: 'Community center in the heart of Castro Valley. Strong connection to local schools with seamless kindergarten transitions.',
      descriptionEs: 'Centro comunitario en el corazón de Castro Valley. Fuerte conexión con escuelas locales con transiciones fluidas a kindergarten.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.PRESCHOOL, AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.FULL_DAY, CareType.BEFORE_AFTER_SCHOOL],
      isActive: true,
    },
    {
      name: 'Canyon Family Child Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '18900 Redwood Road',
      city: 'Castro Valley',
      zipCode: '94546',
      latitude: 37.7012,
      longitude: -122.0567,
      phone: '(510) 555-2002',
      descriptionEn: 'Hillside home with large yard and play structures. Nature-based learning with regular hikes in nearby regional parks.',
      descriptionEs: 'Casa en la ladera con amplio patio y estructuras de juego. Aprendizaje basado en la naturaleza con caminatas regulares en parques regionales cercanos.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },

    // === PLEASANTON/LIVERMORE/DUBLIN (94566, 94568, 94550, 94551, 94588) ===
    {
      name: 'Pleasanton Child Development',
      type: ProviderType.CENTER_BASED,
      address: '4455 Black Avenue',
      city: 'Pleasanton',
      zipCode: '94566',
      latitude: 37.6623,
      longitude: -121.8745,
      phone: '(925) 555-2101',
      email: 'pleasanton@childdev.example.com',
      descriptionEn: 'Premium early learning center in downtown Pleasanton. Low ratios, enrichment programs, and beautiful outdoor spaces.',
      descriptionEs: 'Centro de aprendizaje temprano premium en el centro de Pleasanton. Proporciones bajas, programas de enriquecimiento y hermosos espacios al aire libre.',
      acceptsSubsidy: false,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },
    {
      name: 'Hacienda Family Child Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '4900 Hacienda Drive',
      city: 'Pleasanton',
      zipCode: '94588',
      latitude: 37.6878,
      longitude: -121.8912,
      phone: '(925) 555-2102',
      descriptionEn: 'Near Hacienda Business Park. Ideal for working parents with flexible schedules and professional environment.',
      descriptionEs: 'Cerca del Parque Empresarial Hacienda. Ideal para padres trabajadores con horarios flexibles y ambiente profesional.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },
    {
      name: 'Dublin Ranch Kids Academy',
      type: ProviderType.CENTER_BASED,
      address: '7200 Regional Street',
      city: 'Dublin',
      zipCode: '94568',
      latitude: 37.7123,
      longitude: -121.9234,
      phone: '(925) 555-2103',
      email: 'dublinranch@kidsacademy.example.com',
      descriptionEn: 'Modern facility in Dublin Ranch. STEM-focused curriculum with coding, robotics, and hands-on science.',
      descriptionEs: 'Instalación moderna en Dublin Ranch. Currículo enfocado en STEM con codificación, robótica y ciencia práctica.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.PRESCHOOL, AgeRange.SCHOOL_AGE],
      careTypesOffered: [CareType.FULL_DAY, CareType.BEFORE_AFTER_SCHOOL],
      isActive: true,
    },
    {
      name: 'Livermore Valley Early Learning',
      type: ProviderType.CENTER_BASED,
      address: '2345 First Street',
      city: 'Livermore',
      zipCode: '94550',
      latitude: 37.6817,
      longitude: -121.7656,
      phone: '(925) 555-2104',
      email: 'livermore@earlylearning.example.com',
      descriptionEn: 'Downtown Livermore location with wine country charm. Art-focused curriculum and regular field trips to local attractions.',
      descriptionEs: 'Ubicación en el centro de Livermore con encanto de país vinícola. Currículo enfocado en el arte y excursiones regulares a atracciones locales.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY, CareType.PART_DAY],
      isActive: true,
    },
    {
      name: 'Springtown Family Child Care',
      type: ProviderType.FAMILY_CHILD_CARE,
      address: '780 Bluebell Drive',
      city: 'Livermore',
      zipCode: '94551',
      latitude: 37.6956,
      longitude: -121.7234,
      phone: '(925) 555-2105',
      descriptionEn: 'Established family care in Springtown neighborhood. Large play yard with garden and small animals.',
      descriptionEs: 'Cuidado familiar establecido en el vecindario Springtown. Amplio patio de juegos con jardín y animales pequeños.',
      acceptsSubsidy: true,
      ageRangesServed: [AgeRange.INFANT, AgeRange.TODDLER, AgeRange.PRESCHOOL],
      careTypesOffered: [CareType.FULL_DAY],
      isActive: true,
    },
  ];

  for (const provider of providers) {
    await providerService.createProvider(provider);
  }

  console.log(`Created ${providers.length} providers`);
}
